[package]
name = "libddwaf"
description = "Rust bindings to DataDog/libddwaf"
authors = ["DataDog, Inc. <support@datadoghq.com>"]
version = "1.26.0"
edition = "2021"
categories = ["api-bindings", "security"]
keywords = ["datadog", "security", "waf", "rasp"]
license = "Apache-2.0"
repository = "https://github.com/DataDog/libddwaf-rust"

[dependencies]
libddwaf-sys = { path = "../libddwaf-sys", default-features = false }
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["serde", "static"]
fips = ["libddwaf-sys/fips"]
serde = ["dep:serde"]
static = ["libddwaf-sys/static"]

[lints]
workspace = true
