[package]
name = "libddwaf"
description = "Rust bindings to DataDog/libddwaf"
authors = ["DataDog, Inc. <support@datadoghq.com>"]
version = "1.25.1"
edition = "2021"
categories = ["api-bindings", "security"]
keywords = ["datadog", "security", "waf", "rasp"]
license = "Apache-2.0"
repository = "https://github.com/DataDog/libddwaf-rust"

[dependencies]
libc = "0.2"
serde = { version = "1.0", optional = true }

[build-dependencies]
bindgen = "0.72.0"
flate2 = "1.1"
reqwest = { version = "0.12.22", features = ["blocking"] }
tar = "0.4"

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["serde"]
serde = ["dep:serde"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage, coverage_nightly)'] }
