[package]
name = "libddwaf"
description = "Rust bindings to DataDog/libddwaf"
authors = ["DataDog, Inc. <support@datadoghq.com>"]
version = "1.25.1"
edition = "2021"
categories = ["api-bindings", "security"]
keywords = ["datadog", "security", "waf", "rasp"]
license = "Apache-2.0"
repository = "https://github.com/DataDog/libddwaf-rust"

[dependencies]
libc = "0.2"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
bindgen = "0.72.0"
flate2 = "1.1"
reqwest = { version = "0.12", features = ["blocking"] }
tar = "0.4"

[features]
default = ["serde"]
serde = ["dep:serde"]
serde_test = ["serde", "dep:serde", "dep:serde_json"]
static = []
