[package]
name = "libddwaf"
version = "1.21.0"
edition = "2021"

[dependencies]
libc = "0.2"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
cc = "1.0"
bindgen = "0.69.5"

[features]
default = ["serde", "shared_lib"]
serde = ["dep:serde"]
serde_test = ["dep:serde", "dep:serde_json"]
static_lib = []
shared_lib = []
