[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/*"]

[workspace.package]
authors = ["DataDog, Inc. <support@datadoghq.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/DataDog/libddwaf-rust"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage, coverage_nightly)'] }
