[package]
name = "libddwaf"
version = "1.24.1"
edition = "2021"

[dependencies]
arc-swap = "1.7.1"
libc = "0.2"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
cc = "1.0"
bindgen = "0.72.0"
flate2 = "1.1"
reqwest = { version = "0.12", features = ["blocking"] }
tar = "0.4"

[features]
default = ["serde", "shared_lib"]
serde = ["dep:serde"]
serde_test = ["dep:serde", "dep:serde_json"]
static_lib = []
shared_lib = []
