FROM rust:1.85.0-alpine

RUN apk add --no-cache make musl-dev clang-libclang

RUN --mount=type=bind,source=.,target=/workspace/src,rw                         \
    --mount=type=cache,target=/workspace/src/target,rw                          \
    --mount=type=cache,target=/root/.cargo/git                                  \
    --mount=type=cache,target=/root/.cargo/registry                             \
    cd /workspace/src && make test
