[env]
MACOSX_DEPLOYMENT_TARGET = '12.7'

# bindgen uses `clang-sys` which by default dynamically opens `libclang.so`;
# however this is not supported on Alpine Linux (the usual musl target).
# Enabling the `static` feature of `bindgen`/`clang-sys` creates additional
# build requirements (`libLLVM.a`), which Alpine's `llvm-static` does not
# provide (it has its content presented as many `libLLVM*.a` files). Disabling
# statically linking to the C runtime alleviates this issue, but can result in
# `proc-macro` not being usable; which notably causes doc tests to fail with
# a big linker error.
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
