name: Documentation Site

on:
    pull_request:
    merge_group:
    push:
        branches: [master, main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        name: Build Documentation Site
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - name: Cache
              uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
              with:
                  path: |-
                    ~/.cargo/bin/
                    ~/.cargo/git/db/
                    ~/.cargo/registry/cache/
                    ~/.cargo/registry/index/
                    ~/.rustup/downloads/
                    ~/.rustup/update-hashes/
                    target/
                  key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ github.ref_name }}-${{ hashFiles('.cargo/config.toml', '**/Cargo.toml') }}
                  restore-keys: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ github.ref_name }}-
            - name: Build
              run: cargo +nightly doc --workspace --no-deps
              env:
                   RUSTDOCFLAGS: --enable-index-page -Zunstable-options
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
              with:
                    path: ${{ github.workspace }}/target/doc/
                    retention-days: 7
            - name: Deploy
              if: github.event_name == 'push'
              uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
